### ISSUE TITLE
Come up with a sane way to handle schema versioning and migrations

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-explorer#1]
The database schema is going to change at least once (to add tables required for Shelly). It is rather unlikely that is the only change. Therefore its good to think about this now.

I have previously used the [Persistent](https://hackage.haskell.org/package/persistent) library's migration functionality to manage schema versioning. This consisted of a set of numbered migration files (most SQL, some in Haskell to do more complicated things) like:
```
0000-initial-schema.sql
0001-first-change.sql
....
0010-prepare-for-difficult-change.sql
0011-difficult-change.hs
0012-post-difficult-change.sql
...
```
The SQL migrations would be generated by Persistent, and the Haskell ones hand written. WHen setting up a database from scratch the migrations would be applied in order to get to the most recent version. In addition the database had a table with the current schema version so the migrations could be generated to skip any migration that had already been applied.

However, we are currently thinking of hand writing the schema definition and that means we need to come up with am alternative to the above which hopefully works as well as the above.

**Comment by erikd** [comment]
Probably the first thing to try is to see if Persistent's migration facilities can be used with hand defined schema.

**Comment by rhyslbw** [comment]
> to add tables required for Byron

Do you mean Shelley?

**Comment by erikd** [comment]
Yes, I do :) Corrected it.

**Comment by erikd** [comment]
Probably good to sketch out some extra requirements:

* Need an SQL schema that is well documented (as SQL) so that it can easily be accessed from any other language that can connect to PostgreSQL.
* Easy and sane schema migration as its needed (schema migrations should be idempotent).
* Custom PostgreSQL data types (using PostgreSQL `DOMAIN` statements).
* Custom `VIEW`s.

Definitely possible to all of the above using [Persistent](https://hackage.haskell.org/package/persistent), but the documentation part is the most difficult. Persistent has the big advantage of making the generation of and handling of schema migrations particularly easy.

All of the above can be done with hand written SQL schema, but interfacing with the hand written schema is a bit of a pain in the neck.

**Comment by erikd** [comment]
Meeting the requirements using Persistent would divide the schema handling into three phases:

* **First phase:** Apply some hand written SQL that creates PostgreSQL `DOMAIN` types as needed.
* **Second phase:** Apply one or more Persistent generated migrations which will use the `DOMAIN` types defined in the first phase.
* **Third phase:** Apply hand written SQL to create PostgreSQL `VIEW`s into tables created in the second phase.

**Comment by erikd** [comment]
@parsonsmatt has put together the [persistent-documentation](https://hackage.haskell.org/package/persistent-documentation) package which may help with the documentation aspect.

**Comment by parsonsmatt** [comment]
FWIW, [creating `VIEW`s from `esqueleto` queries](https://github.com/bitemyapp/esqueleto/issues/129) is something we want to implement as well, and it'd be great to have for our stuff at Lumi too. If you would like to collaborate on this feature, it would certainly be welcomed :smile:

**Comment by erikd** [comment]
The way I am going to be adding `VIEW`s (at least for now) is add them in an SQL migration that gets run after the tables are set up. I've got a really nice way of handling schema migrations from a previous job that I want to implement in this project.

**Comment by erikd** [comment]
First pass of the schema management is in PR #3 . @parsonsmatt I have a `VIEW` defined in one of the SQL migrations.

**Comment by erikd** [comment]
Closing this as solved.
