### ISSUE TITLE
webapi: Add 'blockHeight' and 'blockHash' to /api/addresses/summary/{address} endpoint response

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-explorer#130]

**Comment by nnayfack** [comment]
## Provide Address Summary Endpoint Atomic Balance Lookup**

### Changes Needed:
Return the block height and hash that the address summary response is relevant for.

Note: If possible, it would also be helpful to to make an address summary request at an arbitrary block height or hash (low priority relative to above request)

### Relevant Endpoints:
`/api/addresses/summary/{address} `

`https://cardanoexplorer.com/api/addresses/summary/DdzFFzCqrht7Psmn4RhEGMVgfP7H7Qt4fZpjfjJ3gWNtUR6PmuZsEcW4xU5pfuJyfh623SXh9g776hcS43cYUwihBTxScfNzT1ik38bi`

### Why is this required?
We need to be able to correlate the address summary at a specific block, with our internal records at that particular block.

### Desired Response Structure
Main changes are highlighted in yellow.

`GET /api/addresses/summary/DdzFFzCqrht7Psmn4RhEGMVgfP7H7Qt4fZpjfjJ3gWNtUR6PmuZsEcW4xU5pfuJyfh623SXh9g776hcS43cYUwihBTxScfNzT1ik38bi`
```
{ "address": "DdzFFzCqrht7Psmn4RhEGMVgfP7H7Qt4fZpjfjJ3gWNtUR6PmuZsEcW4xU5pfuJyfh623SXh9g776hcS43cYUwihBTxScfNzT1ik38bi"
, "type": "CPubKeyAddress"
, "balance": "0"
, "blockHeight": 12345
, "blockHsh": "be06c81f4ad34d98578b67840d8e65b2aeb148469b290f6b5235e41b75d38572"
, "txList": [...],
}
```

**Comment by dcoutts** [comment]
> Return the block height and hash that the address summary response is relevant for.

I'm not very happy that this is a change that affects only this one endpoint.

This is essentially meta information about the response, much like a server timestamp, but specific for a blockchain API where you want the chain tip point (hash and slot) and block number. So ideally this should be included in the response of every endpoint, in a common way (and with a json structure / naming convention that does not confuse people about what is metadata and what is response data).

**Comment by erikd** [comment]
On discussion it was decided that we must make it obvious that this was meta data that related to the chain tip rather than the query being fulfilled. 
Eg:
```
   , "chainTip" :
          { "blockNumber" : ....
          , "blockSlot": ....
          , "blockHash": ...
          }
```
It should be added to every endpoint where this extra meta data makes sense.
