### ISSUE TITLE
how explorer determines the database name

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-explorer#169]
the explorer currently parses the `pgpass` file to determine the database to connect to.
this is problematic as it prevents me from having a pgpass file:
```
localhost:5432:*:cexplorer:<pw>
```
where I allow the user 'cexplorer' to connect to any db in that server.
And, it even ignores the `PGDATABASE` env var though it is present.

I would prefer that reading from the env var would have priority, and parsing the pgpass file only be a fallback solution.

**Comment by erikd** [comment]
> this is problematic as it prevents me from having a pgpass file:

How does it prevent you from having a `pgpass`file?

If you want a custom setup, just set up your own `pgpass` file (copy the one provided in the repo and modify it to your liking) and point the `PGPASSFILE` environment variable as described in the last point of https://github.com/input-output-hk/cardano-explorer/blob/master/doc/building-running.md

**Comment by erikd** [comment]
Closing this,
