### ISSUE TITLE
pageSize argument is ignored for endpoint: /api/blocks/pages

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-explorer#182]
Run:
`curl http://localhost:8100/api/blocks/pages?page=1&pageSize=20 `

and then change pageSize to different values - it doesn't affect the result

Also - for old explorer we got information about page size limit - `https://cardanoexplorer.com/api/blocks/pages?page=1&pageSize=15`
`{"Left":"We currently support only page size of 10."}`

Which is not present in new one.

**Comment by dcoutts** [comment]
> {"Left":"We currently support only page size of 10."}
>
> Which is not present in new one.

I suggest we keep it that way. I'm sure it was not a deliberate feature to have such a limit.

**Comment by erikd** [comment]
I can confirm the behavior reported by @ArturWieczorek .

However, I agree with @dcoutts that this is definitely something where we should not bother duplicating the behavior of the old explorer. That leaves two options:

* Implement the `pageSize` parameter and make it work correctly.
* Remove the `pageSIze` query parameter all together.

**Comment by erikd** [comment]
The behavior of this endpoint is rather poorly thought out. The original explorer API returns a tuple of:
```
   (current_blockheight_pages, blocks_for_specified_page)
```
which is just rather nasty!

If it is going to do something like that is should return `CChainTip` in place of `current_blockheight_pages`.

**Comment by erikd** [comment]
There are plans to completely redo the webapi so its not worth fixing this before the new API is done.

Closing this.
