### ISSUE TITLE
Epoch table to resolve performance issue with current View

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-explorer#188]
The `Epoch` [View](https://github.com/input-output-hk/cardano-explorer/blob/master/schema/migration-3-0001-20190816.sql#L97-L111) is a poor performer due to the sheer size of the dataset it needs to parse. This is a critical part of the Explorer App, as it's use for client-side logic, and also takes the primary homepage position. The initial load on the _latest epochs_ (see below) makes for a poor UX, and the load on backend services is significant. 

![Screenshot 2019-12-03 at 11 36 38](https://user-images.githubusercontent.com/303881/70006462-61172680-15c1-11ea-8798-804cc37d2ab3.png)

While application caching helps with the load, the optimal place to enable highly performant and low demand queries is at the time of receiving the block, writing to an `epoch` table instead of the view calculating the result.

**Comment by erikd** [comment]
This epoch view in the web UI is a query on a view named `Epoch`. It seems that this view is recalculated for every query which is a bit dumb. This suggests this should be a `table` rather than `view`. The problem is how to maintain this table. 

One possibility would be to update this table on every new block but somewhat nasty.

Another possibility is to only update the epoch when the epoch is known to be stable (ie 2160 slots into the next epoch).

**Comment by rhyslbw** [comment]
> One possibility would be to update this table on every new block but somewhat nasty.

Not sure I agree it's nasty, `output`, `transactionsCount`, `lastBlockTime` increment with every block, so the natural place to do it. Waiting for the end of the epoch won't replace the view we currently have

**Comment by rhyslbw** [comment]
@manveru, @craigem, and I found an edge-case debugging a testing deployment with the current `Epoch` view implementation. While it will only occur in staging and testing environments when there are no transactions, it is currently a blocker.
cc @disassembler

**Comment by dcoutts** [comment]
Materialised views is another possibility.

**Comment by erikd** [comment]
Hmmm. `matertialized views` does look interesting, but I am not sure it will help up here. The probeem is that `REFRESH MATERIALIZED VIEW epoch;` which would refresh the whole view, not just the current epoch. Refreshing the whole view (ie *all* epochs) every 20 seconds sounds like a lot of work and in fact an increasing amount of work as the blockchain becomes longer.

An alternative would be to manually manage this table. Doing this allows a couple of tricks to maximize performance :
* When syncing the chain, only populate the `Epoch` table for each epoch at the end of each epoch.
* When following the chain update the current epoch's entry on each new block, re-running the calculation for the whole of the current epoch (this will just do the right thing on rollbacks that do not cross epoch boundaries).
* On rollback's the that cross epoch boundaries. recalculate the epoch entry for both the current and the previous epochs.

**Comment by rhyslbw** [comment]
👍 agree, this is a sensible strategy

**Comment by erikd** [comment]
Implementation plan:

* ~Remove `Epcoh` view.~
* ~Add `Epoch` table to the DB schema.~
* Implement a query that populates an `Epoch` struct.
* Update insertion of boundary block to include update of epoch entry for the epoch just finished.
* Add code to detect the difference between syncing the chain (we are more than 2160 block behind) and following the chain.
* When following the chain, update the current epoch entry on each new block.

**Comment by rhyslbw** [comment]
Best to use `epoch` for the table name, as I can then add the `Epoch` view for conformance with the API

**Comment by erikd** [comment]
In the Haskell world its `Epoch` but in Postgres it will be `epoch` (that is how its managed by the Persistent DSL).

**Comment by dcoutts** [comment]
If we really need a consistent cache then sure this is the way to do it, but it means the exporter becomes specific to the explorer frontend, but we need to have a generic exporter for multiple use cases. We cannot build in every cache for every application.

So lets review if we either:
1. can do it without changing the exporter (using db tricks)
2. or make the exporter into a library to allow an explorer-specific exporter while keeping a generic one

**Comment by erikd** [comment]
>  it means the exporter becomes specific to the explorer frontend

@dcoutts Why is that? The `Epoch` table is just another table. Data in that table is just aggregated from data in other tables. The table would be maintained by the node.

**Comment by erikd** [comment]
This can be closed. Its done!
