### ISSUE TITLE
Build mainnet-byron-proxy failed

### ISSUE THREAD

**Issue by Victoryfan** [input-output-hk/cardano-explorer#202]
When i build the scripts.mainnet.proxy, it failed.

**Comment by erikd** [comment]
Please delete that screen shot (which I am unable to read) and instead paste the text.

**Comment by Victoryfan** [comment]
> Please delete that screen shot (which I am unable to read) and instead paste the text.

make[1]: Leaving directory '/tmp/nix-build-binutils-2.31.1.drv-0/binutils-2.31.1'
building '/nix/store/givkj88d6pxhkxig120shqvdb8a2mrvh-binutils-wrapper-2.31.1.drv'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
installing
post-installation fixup
checking for references to /tmp/nix-build-binutils-wrapper-2.31.1.drv-0/ in /nix/store/7dmz5jkmfzbb13pjav1zym86hnxarnd5-binutils-wrapper-2.31.1...
Using dynamic linker: '/nix/store/31rpy9zrh8xb2wfx9ibp4amkc9pb9m05-bootstrap-stage0-glibc/lib/ld-linux-x86-64.so.2'
building '/nix/store/zji169bsr9xplab7qqzmk0477s2646dz-bootstrap-stage2-gcc-wrapper.drv'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
installing
post-installation fixup
checking for references to /tmp/nix-build-bootstrap-stage2-gcc-wrapper.drv-0/ in /nix/store/78zpigbkgnwpgi5w6c1i76inr1iq8ci2-bootstrap-stage2-gcc-wrapper...
building '/nix/store/2j4m0pb0dlq9yrv0hai2rxjdfj79pv1l-bootstrap-stage2-stdenv-linux.drv'...
building '/nix/store/gv1f3jwbsmdmrzi8kkjzv5g0jbxpr980-linux-headers-4.19.16.drv'...
unpacking sources
unpacking source archive /nix/store/8javli69jhj3bkql2c35gsj5vl91p382-linux-4.19.16.tar.xz
tar: linux-4.19.16/arch/arm64/boot/dts/arm: Directory renamed before its status could be extracted
tar: linux-4.19.16/arch/arm64/boot/dts: Directory renamed before its status could be extracted
tar: linux-4.19.16/arch/arm64/boot: Directory renamed before its status could be extracted
tar: linux-4.19.16/arch/arm64: Directory renamed before its status could be extracted
tar: linux-4.19.16/arch: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
do not know how to unpack source archive /nix/store/8javli69jhj3bkql2c35gsj5vl91p382-linux-4.19.16.tar.xz
builder for '/nix/store/gv1f3jwbsmdmrzi8kkjzv5g0jbxpr980-linux-headers-4.19.16.drv' failed with exit code 1
building '/nix/store/28frm7y583b1nxb6cjrqlb4izq95fddz-expand-response-params.drv'...
cannot build derivation '/nix/store/mfxvmhph0fkmn0z9cq1wlr8pbbrywhaj-glibc-2.27.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hxw7ls07nrkygbfrbk9gb7vml534rjfp-stdenv-linux.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/ddxvn5cjlcwhxvhqg0xjrk5grbh346ds-haskell-nix.json.drv': 1 dependencies couldn't be built
error: build of '/nix/store/ddxvn5cjlcwhxvhqg0xjrk5grbh346ds-haskell-nix.json.drv' failed
(use '--show-trace' to show detailed location information)

**Comment by erikd** [comment]
> When i build the scripts.mainnet.proxy, it failed.

What *exact* command are you running in which git checkout?

Are you building on Arm64?

**Comment by Victoryfan** [comment]
> > When i build the scripts.mainnet.proxy, it failed.
> 
> What _exact_ command are you running in which git checkout?
> 
> Are you building on Arm64?

I build it on linux, and i didn't run git checkout, i don't know what's version should checkout.
I just do command with this: https://github.com/input-output-hk/cardano-explorer/blob/master/doc/building-running.md

**Comment by erikd** [comment]
I meant, what directory are you in?

This:
>  linux-4.19.16/arch/arm64/

suggests that its `arm64` and not `amd64`. That is *very* important information.

However, "scripts.mainnet.proxy" is not a valid Nix build target for this repository (cardano-exploter).  The repo for the proxy is [cardano-byron-proxy](https://github.com/input-output-hk/cardano-byron-proxy/).

**Comment by Victoryfan** [comment]
> I meant, what directory are you in?
> 
> This:
> 
> > linux-4.19.16/arch/arm64/
> 
> suggests that its `arm64` and not `amd64`. That is _very_ important information.
> 
> However, "scripts.mainnet.proxy" is not a valid Nix build target for this repository (cardano-exploter). The repo for the proxy is [cardano-byron-proxy](https://github.com/input-output-hk/cardano-byron-proxy/).
I'm puzzled with what you said, i should build and run cardano-byron-proxy follow this 👍 :https://github.com/input-output-hk/cardano-explorer/blob/master/doc/building-running.md
,right?

**Comment by erikd** [comment]
Those are instructions for setting up the Bryon Proxy but Byron Proxy is a separate project and problems building that project should be raised in that repo, not this one.

The only possible valid issue with that document that that it is incorrect and needs fixing. That is not the case here.

**Comment by erikd** [comment]
Closing this as unrelated to cardano-explorer.
