### ISSUE TITLE
Why is there no broadcast api

### ISSUE THREAD

**Issue by vae520283995** [input-output-hk/cardano-explorer#204]
I signed the transaction but couldn't find the api for broadcast.

**Comment by erikd** [comment]
The component to allow transaction submission is a [separate component](https://github.com/input-output-hk/cardano-explorer/tree/master/cardano-tx-submit) that has only just merged today. It has not yet been properly QAed or validated.

**Comment by vae520283995** [comment]
> The component to allow transaction submission is a [separate component](https://github.com/input-output-hk/cardano-explorer/tree/master/cardano-tx-submit) that has only just merged today. It has not yet been properly QAed or validated.

Is there a demo used

**Comment by erikd** [comment]
> Is there a demo used

Sorry, I do not understand the question.

**Comment by vae520283995** [comment]
> Sorry, I do not understand the question.

How can I use this tx-submit API

**Comment by erikd** [comment]
Please wait until it has been QA-ed, it's use has properly documented and this component is formally released.
