### ISSUE TITLE
Negative balance? [BUG]

### ISSUE THREAD

**Issue by Fell-x27** [input-output-hk/cardano-explorer#207]
I'm not sure that it's a right repo for my issue, but there is a problem with ITN Explorer:

There is an address:
addr1s52wv42ktwms47j5xgxdkfqhpc234ehv2d692p3lv24f3x74cak4wv4mnnk

JCLI says:
171.133162 ADA

Explorer says:
-400.800000 ADA

Link: [https://shelleyexplorer.cardano.org/en/address/addr1s52wv42ktwms47j5xgxdkfqhpc234ehv2d692p3lv24f3x74cak4wv4mnnk/](url)

Actual behaviour: showing wrong balance.
Expected behaviour: showing real balance.

**Comment by erikd** [comment]
Sorry, the explorer for the ITN is not this explorer. I am in the process of trying to figure out who in IOHK is responsible for the ITN explorer so this issue can be redirected to the right place.

**Comment by DimitrisPoulo** [comment]
You can raise ITN explorer issues here: https://github.com/input-output-hk/shelley-testnet-explorer/issues/new hope this helps

**Comment by erikd** [comment]
Closing this.
