### ISSUE TITLE
Changes in cardano-foundation/incentived-testnet-stakepool-registry not reflected in explorer

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/cardano-explorer#212]
My pull request #1023 to cardano-foundation/incentivied-testnet-stakepool-registry to update the name, ticker, description, and homepage for stake pool with hash 9ebb7c1efc6262dbbad14ba9ec6b1654d8caf7f9ee37b92cd719ebe8fe11bdaf was merged 7 days ago but the explorer still shows the old information.
The old info was CCP1, Cardano Community Pool, cardanocommunitypool.com, etc. and the new info is SQUID, Squid Pool, squidpool.com, etc.

I'm not sure whether this info is updated in the explorer automatically or manually.

If it is manual, please update the pool information.
If it is automatic, there may be an issue with the update mechanism.

Thanks!

**Comment by erikd** [comment]
This is not the explorer for the Incentivized Test Net.

For the ITN this is the repo you want: https://github.com/input-output-hk/shelley-testnet-explorer/issues/new .

**Comment by shawnim** [comment]
Thanks for the reply.
That link does not work for me.
Perhaps that repo is private?
Or is it shelley-testnet or jormungandr-explorer perhaps?

**Comment by erikd** [comment]
@DimitrisPoulo Is that the right repo? Should it be be public?
