### ISSUE TITLE
Store TX bodies for hardware wallet support

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/cardano-explorer#258]
The way that hardware wallets work in Byron-era is that the hardware wallets is that instead of simply accepting a UTXO, it instead asks for the whole TX body where the UTXO was created that way it  can verify the witness

This means that we had to add the TX body to the Postgres database for the Icarus project (https://github.com/Emurgo/project-icarus-importer/pull/5) . From Yoroi, we have an endpoint `api/txs/txBodies` that takes in tx hashes and returns the body for those transactions. We use this whenever a hardware wallet user needs to make a transaction.

In order to migrate from our HTTP bridge to this new codebase, we need the TX bodies stores so we can continue to provide this endpoint.

**Comment by dcoutts** [comment]
This is out of scope for the explorer DB and REST API. They do not cover raw blocks or transactions, just the structured information from blocks and transactions.

It is a reasonable feature request for Adrestia.
