### ISSUE TITLE
build cardano-explorer failed

### ISSUE THREAD

**Issue by freddieee** [input-output-hk/cardano-explorer#278]
System: Ubuntu 18.04

Hi Team, I am following the instruction(https://github.com/input-output-hk/cardano-explorer/blob/master/doc/building-running.md). When I tried to build the `mainnet-byron-proxy` with `nix-build -A scripts.mainnet.proxy -o mainnet-byron-proxy`,
error message:

`trace: Using index-state: 2020-01-31T00:00:00Z for cardano-byron-proxy building '/nix/store/p02j0924vd4svr4n1g8laxzl2c3vf9xp-happy-plan-to-nix-pkgs.drv'... error: moving build output '/nix/store/mzi2s0fscckbqz3bjmpjpami8zssygym-happy-plan-to-nix-pkgs' from the sandbo x to the Nix store: Permission denied (use '--show-trace' to show detailed location information)`

when I tried to run `nix-build -A cardano-explorer-node -o explorer-node`,
I got the following error message

`
Makefile:11843: recipe for target 'tests/test-suite.log' failed
make[4]: *** [tests/test-suite.log] Error 1
make[4]: Leaving directory '/build/coreutils-8.29'
Makefile:11949: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/build/coreutils-8.29'
Makefile:12204: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/build/coreutils-8.29'
Makefile:11729: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/build/coreutils-8.29'
Makefile:12206: recipe for target 'check' failed
make: *** [check] Error 2
builder for '/nix/store/rik10c4cc3kcmlfjkzy0hq5p1vsrhvpz-coreutils-8.29.drv' failed with exit
 code 2
cannot build derivation '/nix/store/9rzxc30b9x87dpn7qvzlw5m2idqpinc3-gcc-wrapper-7.3.0.drv': 
1 dependencies couldn't be built
cannot build derivation '/nix/store/xd4f547wd0ri6im0inq0zsnhcnbp5avq-git-2.18.1.drv': 1 depen
dencies couldn't be built
cannot build derivation '/nix/store/p46j2csg16z3dcr0b6575p1vbzpj62xj-stdenv-linux.drv': 1 dep
endencies couldn't be built
cannot build derivation '/nix/store/w87373aisijvzw1l3n8bk0fj7nncizgw-stdenv-linux.drv': 1 dep
endencies couldn't be built
cannot build derivation '/nix/store/wn80v7702dr1672i74k60aa1z2jrdw28-haskell.nix-aa10a0b.drv'
: 1 dependencies couldn't be built
error: build of '/nix/store/wn80v7702dr1672i74k60aa1z2jrdw28-haskell.nix-aa10a0b.drv' failed
`

**Comment by erikd** [comment]
That error message is from when Nix tries to rebuild `coreutils` which is a standard Linux component and unrelated to this explorer.

Please try `git pull` and then rebuild.

**Comment by hamishmack** [comment]
I think this is related to https://github.com/NixOS/nix/issues/2984.

**Comment by freddieee** [comment]
> That error message is from when Nix tries to rebuild `coreutils` which is a standard Linux component and unrelated to this explorer.
> 
> Please try `git pull` and then rebuild.

It still doesn't work and output the same error.  can i avoid rebuilding `coreutils`?

**Comment by erikd** [comment]
That means it is likely to be that Nix bug.

Further more this repo is being split up, with parts going to `cardano-rest` and others going to `cardano-db-sync`. You should probably ignore this repo as it will be deprecated soon.

**Comment by erikd** [comment]
Closing this.
