### ISSUE TITLE
Error policies for the explorer

### ISSUE THREAD

**Issue by coot** [input-output-hk/cardano-explorer#82]
The explorer should not silently go down with an exception, but retry subscription.
This is a blocker for releasing the explorer.

**Comment by erikd** [comment]
Is this something to be fixed in the explorer or in the network/consensus layer?

**Comment by karknu** [comment]
It will be changes in the NodeToClient interface in the network layer as well as in the explorer to use the new interface.

**Comment by karknu** [comment]
Implemented by #102 .
