### ISSUE TITLE
webapi: Implement /api/stats/txs

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-explorer#96]
From https://cardanodocs.com/technical/explorer/api/#path--api-stats-txs

**Comment by erikd** [comment]
Have no idea what this is supposed to do. Currently getting:
```
nix@nix:~/cardano-explorer$ ./curl /api/stats/txs

New Explorer
{"Right":[157048,[]]}

Cardano Explorer
{"Right": [326038,
    [ ["8dd116ec05dd6eaf96d2cec91e9d55ab5cc51f8048647d86d7e5382cce76665c",187]
    , ["3e4759d242df6f67e0504544ceab0f4c8f66b4e29db391682cb3b3facdc14487",434]
    , ["d6d7c1da08db995bb8df696719f1b25eafe93e29d7e15522d657ef803f919884",258]
    ]
]}
```

**Comment by cleverca22** [comment]
you give it the page number for a set of blocks (if the page# is missing, it uses the latest page)

it will then return the block-page-number (326038) and a list of transaction hashes and byte size, across all blocks on that page

https://github.com/input-output-hk/cardano-sl/blob/develop/explorer/src/Pos/Explorer/Web/Server.hs#L848-L881

thats what it appears to be doing

**Comment by erikd** [comment]
Ok, I have the page number part sorted out.

In order to print the size of the tx will need to store that value in the database and that cannot be done with just a database migration. It will need a schema update and a full resync of the database.

**Comment by erikd** [comment]
Have now added a size table and can now get the correct set of `tx` hashes for all queries, but the `tx` sizes are incorrect.

**Comment by erikd** [comment]
This is weird! The old explorer code base uses the `biSize` function (defined as `BSL.length . serialize`) to get the size and I am using `BS.length . serialize` (and have also tried `BSL.length . serialize`

**Comment by erikd** [comment]
Ok, fixed the size issue.

The explorer returns a `(PageNumber, [(CTxHash, Word64)])` where the page number is the current block height regardless of which page number of being ask for. As long as both the old and the new explorer are in sync they should give the same result.

Sample queries:

* `/api/stats/txs`
* `/api/stats/txs?page=1`
* `/api/stats/txs?page=4000`
