### ISSUE TITLE
webapi: Implement /api/txs/summary/{txHash}

### ISSUE THREAD

**Issue by erikd** [input-output-hk/cardano-explorer#99]
From https://cardanodocs.com/technical/explorer/api/

**Comment by erikd** [comment]
Currently has a UTF-8 decode problem.

**Comment by cleverca22** [comment]
i ran into similar when a raw hash was being shoved into some json without hex encoding it

**Comment by erikd** [comment]
Have sorted out the hash issues, but the tx timestamps are still incorrect. Have pulled this endpoint into its own file in PR #111 and will come back to this.

**Comment by erikd** [comment]
This endpoint is very poorly named.

For a transaction that is already on the block chain the existing explorer returns:
```
{"Left":"Transaction missing in MemPool!"}
```
which means that this endpoint *only* operates on the mempool and the current explorer backend does not maintain a mempool.

**Comment by erikd** [comment]
This actually doesn't work in the current explorer because nodes do not forward pending transactions to the explorer nodes.

Closing this as "won't fix".
